### ISSUE TITLE
Issue with mixed whitespace

### ISSUE THREAD

**Issue by Gruntfuggly** [byi8220/indented-block-highlighting#1] opened 2018-02-27 09:43 UTC
First, thanks fo the extension!

When the indentation at the start of the line has different whitespace, it thinks the block has ended:

![image](https://user-images.githubusercontent.com/376658/36721367-a347cb24-1ba2-11e8-8a8f-4952a482e4e1.png)

**Comment by byi8220** [comment] 2018-02-28 06:10
Issue noted, I updated it to consider tabs to be **arbitrarily** 4 spaces as is the default for VSC. The test case in that picture should work as intended now.
This is for performance reasons (polling the tab size is surprisingly expensive), and that I am unaware of how to find the current document's tab size (not editor.tabSize, it seems.)

**Comment by Gruntfuggly** [comment] 2018-02-28 09:05
Working nicely now - thanks. 

A lot of the settings seem to be write only where you would expect them to be readable - like the current comment characters for the language.

Could you cache the tab size from the user configuration and update it if the configuration is modified?

**Comment by byi8220** [comment] 2018-02-28 13:31
That's what my current idea is. I'm having two issues with this though

1) The editor.tabSize from the user config is the default. Normally a file's indent size lands on that, but the user can change it at will so using it may cause issues. I'm trying to access the document (or active editor's) properties. Likely possible but I haven't looked into it too much.

2) For some reason pulling in configs causes a serious performance drop.

**Comment by Gruntfuggly** [comment] 2018-02-28 15:37
How are you fetching the configuration? I've got a similar extension to yours (which I based on somebody elses) that gets the configuration multiple times on each editor update and I don't see performance problems?

I use the following to get some flags based on the language type (not officially supported, but it works):
```
var language = vscode.window.activeTextEditor.document.languageId;
var config = vscode.workspace.getConfiguration().get( '[' + language + ']' )
```

**Comment by byi8220** [comment] 2018-03-01 16:52
The issue appears to be fixed now with no real performance loss. I did find a new issue which is written down in the readme.

Thank you so much for testing and pointing out issues. If any other issues arise, bringing them up is greatly appreciated.

**Closed as completed by byi8220** 2018-03-01 16:52 UTC
Labels: bug
